name: Build

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  build-unix:
    strategy:
      fail-fast: false       
      matrix:
        clib: [glibc, musl]
        include:
          - clib: glibc
            os: ubuntu-24.04
          - clib: musl
            os: ubuntu-latest
            container: alpine:latest
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.container }}
      
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies for glibc
      run: |
        sudo apt update
        sudo apt install -y qt6-base-dev qt6-tools-dev qt6-svg-dev libgl1-mesa-dev libxkbcommon-dev libvulkan-dev qmake6 smartmontools qt6ct patchelf xvfb strace wget
      if: ${{ matrix.clib == 'glibc' }}
    - name: Install dependencies for musl
      run: |
        apk add git cmake make gcc g++ curl gcompat qt6-qtbase-dev qt6-qttools-dev qt6-qtbase-x11 qt6-qtsvg breeze smartmontools
        git config --global --add safe.directory '*'
      if: ${{ matrix.clib == 'musl' }}
      
    - name: Build
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE:STRING=MinSizeRel -DQT_VERSION_MAJOR=6 -DENABLE_TRANSLATIONS=ON
        cmake --build build

    - name: Package AppImage
      run: |
        export APPIMAGE_EXTRACT_AND_RUN=1 ARCH=x86_64 VERSION=anylinux
        LIB4BN="https://raw.githubusercontent.com/VHSgunzo/sharun/refs/heads/main/lib4bin"
        APPIMAGETOOL="https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-$ARCH.AppImage"
        wget "$APPIMAGETOOL" -O appimagetool-static.AppImage
        chmod a+x *.AppImage
        chmod a+x .github/scripts/smartctl
         
        mkdir -p AppDir/shared/bin/../share/applications
        cp build/QDiskInfo AppDir/shared/bin/
        cp dist/QDiskInfo.desktop AppDir/shared/share/applications
        cp dist/QDiskInfo.svg AppDir/QDiskInfo.svg
        ln -s ./shared AppDir/usr
        cd AppDir
        wget "$LIB4BN" -O ./lib4bin
        chmod +x ./lib4bin
        xvfb-run -d -- ./lib4bin -p -v -e -r -s ./shared/bin/QDiskInfo
        ln -s ./bin/QDiskInfo ./AppRun
        cd ..

        ./appimagetool-static.AppImage AppDir

    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: QDiskInfo-anylinux-AppImage
        path: ./QDiskInfo*.AppImage

    - name: Upload Binaries
      uses: actions/upload-artifact@v4
      with:
        name: QDiskInfo-Qt6-${{ matrix.clib }}-bin
        path: ./build/QDiskInfo
        
