name: Build

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container: ghcr.io/pkgforge-dev/archlinux:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm \
          base-devel     \
          breeze         \
          clang          \
          cmake          \
          libxkbcommon   \
          mesa           \
          patchelf       \
          qt6-base       \
          qt6ct          \
          qt6-svg        \
          qt6-tools      \
          smartmontools  \
          vulkan-devel   \
          wget

    - name: Build
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE:STRING=MinSizeRel -DQT_VERSION_MAJOR=6 -DENABLE_TRANSLATIONS=ON
        cmake --build build

    - name: Package AppImage
      run: |
        chmod +x ./qdiskinfo-appimage.sh
        ./qdiskinfo-appimage.sh
        
    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: QDiskInfo-anylinux-AppImage
        path: ./QDiskInfo*.AppImage

    - name: Upload Binaries
      uses: actions/upload-artifact@v4
      with:
        name: QDiskInfo-Qt6-bin
        path: ./build/QDiskInfo
