name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      actions: read
      security-events: write
      contents: write
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - arch: aarch64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
    container:
      image: ghcr.io/pkgforge-dev/archlinux:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm \
            base-devel     \
            breeze         \
            clang          \
            cmake          \
            libxkbcommon   \
            mesa           \
            patchelf       \
            qt6-base       \
            qt6ct          \
            qt6-svg        \
            qt6-tools      \
            smartmontools  \
            vulkan-devel   \
            wget

      - name: Build
        run: |
          cmake -Bbuild -DCMAKE_BUILD_TYPE:STRING=MinSizeRel -DQT_VERSION_MAJOR=6 -DENABLE_TRANSLATIONS=ON
          cmake --build build

      - name: Package AppImage
        run: |
          chmod +x ./qdiskinfo-appimage.sh
          ./qdiskinfo-appimage.sh

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: QDiskInfo-${{ matrix.arch }}-AppImage
          path: ./QDiskInfo*.AppImage*

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: QDiskInfo-Qt6-${{ matrix.arch }}-bin
          path: ./build/QDiskInfo
